// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/GoSimplicity/template/internal/api/http"
	"github.com/GoSimplicity/template/internal/event/template"
	"github.com/GoSimplicity/template/internal/repository"
	"github.com/GoSimplicity/template/internal/repository/cache"
	"github.com/GoSimplicity/template/internal/repository/dao"
	"github.com/GoSimplicity/template/internal/service"
)

import (
	_ "github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp() *Cmd {
	logger := InitLogger()
	v := InitMiddlewares(logger)
	db := InitDB()
	templateDAO := dao.NewTemplateDAO(db)
	client := InitRedis()
	templateCache := cache.NewTemplateCache(client)
	saramaClient := InitSaramaClient()
	syncProducer := InitSyncProducer(saramaClient)
	producer := template.NewTemplateSaramaSyncProducer(syncProducer, logger)
	templateRepository := repository.NewTemplateRepository(templateDAO, logger, templateCache, producer)
	templateService := service.NewTemplateService(templateRepository)
	templateHandler := http.NewTemplateHandler(templateService)
	engine := InitWeb(v, templateHandler)
	templateEventConsumer := template.NewTemplateEventConsumer(saramaClient, syncProducer, logger)
	v2 := InitConsumers(templateEventConsumer)
	cmd := &Cmd{
		Server:   engine,
		Consumer: v2,
	}
	return cmd
}
